pipeline:
  build:
    image: metwork/mfservplugins-${OS_VERSION}-buildimage:master
    commands:
      - /opt/metwork-mfserv/bin/mfserv_wrapper make release
    when:
      event: [push, pull_request]

matrix:
  OS_VERSION:
    - centos7

branches: [ master, integration, ci_*, pci_* ]
